In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
dataset = pd.read_csv('Desktop/datathon.csv', delimiter = ';')

In [4]:
dataset.head()

ID Motorway             SR   NR TR  VR  SUR1  SUR2  SUR3   UR  ... BR  MR  \
0   1       A1      82.122666  1.0  1   4   6.0     2    10  0.0  ...  0   0   
1   2       A1 -180534.465668  1.0  5   1  10.0     6    10  3.0  ...  1   0   
2   3       A1    1193.589181  1.0  5   1   NaN     6    10  3.0  ...  1   0   
3   4       A1     629.864146  1.0  5   0   6.0    10     2  3.0  ...  0   0   
4   5       A1 -180803.798829  2.0  1   4   NaN     2     6  0.0  ...  5   0   

    CR  Green Frogs Brown Frogs  Common Toad  Fire-Bellied Toad  Tree Frog  \
0  NaN            0           0            0                  0          0   
1  1.0            0           1            1                  0          0   
2  1.0            0           1            1                  0          0   
3  1.0            0           0            1                  0          0   
4  1.0            0           1            1                  1          0   

   Common Newt  Great Crested Newt  
0            0                   0  
1            1                   0  
2            1                   0  
3            0                   0  
4            1                   1  

[5 rows x 23 columns]

In [5]:
dataset.dtypes

ID                      int64
Motorway               object
SR                    float64
NR                    float64
TR                     object
VR                      int64
SUR1                  float64
SUR2                    int64
SUR3                    int64
UR                    float64
FR                     object
OR                    float64
RR                    float64
BR                      int64
MR                     object
CR                    float64
Green Frogs             int64
Brown Frogs             int64
Common Toad             int64
Fire-Bellied Toad       int64
Tree Frog               int64
Common Newt             int64
Great Crested Newt      int64
dtype: object

In [6]:
dataset['Motorway'].unique()

array(['A1', 'S52'], dtype=object)

In [7]:
dataset['TR'].unique()

array(['1', '5', '12', '?', '14', '15', '11', '2', '7'], dtype=object)

In [8]:
dataset['FR'].unique()

array(['0', '1', '4', '2', '3', '?'], dtype=object)

In [9]:
dataset['MR'].unique()

array(['0', '?', '2', '1'], dtype=object)

In [10]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
dataset['Motorway'] = le.fit_transform(dataset['Motorway'])

In [11]:
dataset['Motorway'].unique()

array([0, 1])

In [12]:
dataset['TR'] = le.fit_transform(dataset['TR'])

In [13]:
dataset['TR'].unique()

array([0, 6, 2, 8, 3, 4, 1, 5, 7])

In [15]:
dataset['MR'] = le.fit_transform(dataset['MR'])
dataset['MR'].unique()

array([0, 3, 2, 1])

In [16]:
dataset.head()

ID  Motorway             SR   NR  TR  VR  SUR1  SUR2  SUR3   UR  ... BR  \
0   1         0      82.122666  1.0   0   4   6.0     2    10  0.0  ...  0   
1   2         0 -180534.465668  1.0   6   1  10.0     6    10  3.0  ...  1   
2   3         0    1193.589181  1.0   6   1   NaN     6    10  3.0  ...  1   
3   4         0     629.864146  1.0   6   0   6.0    10     2  3.0  ...  0   
4   5         0 -180803.798829  2.0   0   4   NaN     2     6  0.0  ...  5   

   MR   CR  Green Frogs  Brown Frogs  Common Toad  Fire-Bellied Toad  \
0   0  NaN            0            0            0                  0   
1   0  1.0            0            1            1                  0   
2   0  1.0            0            1            1                  0   
3   0  1.0            0            0            1                  0   
4   0  1.0            0            1            1                  1   

   Tree Frog  Common Newt  Great Crested Newt  
0          0            0                   0  
1          0            1                   0  
2          0            1                   0  
3          0            0                   0  
4          0            1                   1  

[5 rows x 23 columns]

In [18]:
print(dataset)

      ID  Motorway             SR   NR  TR  VR  SUR1  SUR2  SUR3   UR  ... BR  \
0      1         0      82.122666  1.0   0   4   6.0     2    10  0.0  ...  0   
1      2         0 -180534.465668  1.0   6   1  10.0     6    10  3.0  ...  1   
2      3         0    1193.589181  1.0   6   1   NaN     6    10  3.0  ...  1   
3      4         0     629.864146  1.0   6   0   6.0    10     2  3.0  ...  0   
4      5         0 -180803.798829  2.0   0   4   NaN     2     6  0.0  ...  5   
..   ...       ...            ...  ...  ..  ..   ...   ...   ...  ...  ... ..   
191  192         1  115998.517892  9.0   0   3   2.0     9     6  3.0  ...  0   
192  193         0     164.442663  1.0   3   2   1.0     2     7  0.0  ...  1   
193  194         1    -866.209002  1.0   2   2  10.0    10     2  0.0  ...  5   
194  195         1   27369.210342  3.0   0   2  10.0     6     1  3.0  ...  0   
195  196         1     889.098487  1.0   0   4   9.0     2    10  0.0  ...  0   

     MR   CR  Green Frogs  

In [28]:
X = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1].values

In [29]:
dataset.dtypes

ID                      int64
Motorway                int64
SR                    float64
NR                    float64
TR                      int64
VR                      int64
SUR1                  float64
SUR2                    int64
SUR3                    int64
UR                    float64
FR                      int64
OR                    float64
RR                    float64
BR                      int64
MR                      int64
CR                    float64
Green Frogs             int64
Brown Frogs             int64
Common Toad             int64
Fire-Bellied Toad       int64
Tree Frog               int64
Common Newt             int64
Great Crested Newt      int64
dtype: object

In [30]:
dataset['FR'] = le.fit_transform(dataset['FR'])

In [31]:
dataset.dtypes

ID                      int64
Motorway                int64
SR                    float64
NR                    float64
TR                      int64
VR                      int64
SUR1                  float64
SUR2                    int64
SUR3                    int64
UR                    float64
FR                      int64
OR                    float64
RR                    float64
BR                      int64
MR                      int64
CR                    float64
Green Frogs             int64
Brown Frogs             int64
Common Toad             int64
Fire-Bellied Toad       int64
Tree Frog               int64
Common Newt             int64
Great Crested Newt      int64
dtype: object

In [33]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, :])
X[:, :] = imputer.transform(X[:, :])

In [35]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [36]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [37]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

KNeighborsClassifier()

In [38]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[33  1]
 [ 3  3]]


0.9

In [39]:
from sklearn.model_selection import train_test_split
X_trainr, X_testr, y_trainr, y_testr = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [40]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_trainr = sc.fit_transform(X_trainr)
X_testr = sc.transform(X_testr)

In [41]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(X_trainr, y_trainr)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

In [42]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_predr = classifier.predict(X_test)
cm = confusion_matrix(y_testr, y_predr)
print(cm)
accuracy_score(y_testr, y_predr)

[[33  1]
 [ 6  0]]


0.825

In [43]:
import tensorflow as tf

2022-09-22 17:21:49.995600: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2022-09-22 17:21:50.054271: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-09-22 17:21:50.054285: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


In [44]:
from sklearn.model_selection import train_test_split
X_train1, X_test1, y_train1, y_test1 = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [45]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train1 = sc.fit_transform(X_train1)
X_test1 = sc.transform(X_test1)

In [61]:
ann = tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(units=3, activation='relu'))
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [62]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [63]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 30)

Epoch 1/30
5/5 [==============================] - 0s 1ms/step - loss: 0.5875 - accuracy: 0.8846
Epoch 2/30
5/5 [==============================] - 0s 1ms/step - loss: 0.5781 - accuracy: 0.8846
Epoch 3/30
5/5 [==============================] - 0s 973us/step - loss: 0.5692 - accuracy: 0.8846
Epoch 4/30
5/5 [==============================] - 0s 1ms/step - loss: 0.5603 - accuracy: 0.8846
Epoch 5/30
5/5 [==============================] - 0s 979us/step - loss: 0.5518 - accuracy: 0.8846
Epoch 6/30
5/5 [==============================] - 0s 1ms/step - loss: 0.5437 - accuracy: 0.8846
Epoch 7/30
5/5 [==============================] - 0s 1ms/step - loss: 0.5351 - accuracy: 0.8846
Epoch 8/30
5/5 [==============================] - 0s 1ms/step - loss: 0.5271 - accuracy: 0.8846
Epoch 9/30
5/5 [==============================] - 0s 1ms/step - loss: 0.5188 - accuracy: 0.8846
Epoch 10/30
5/5 [==============================] - 0s 981us/step - loss: 0.5110 - accuracy: 0.8846
Epoch 11/30
5/5 [================

In [64]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

2/2 [==============================] - 0s 2ms/step
[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]


In [65]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[34  0]
 [ 6  0]]


0.85

In [66]:
from sklearn.model_selection import train_test_split
X_train2, X_test2, y_train2, y_test2 = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [69]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train2 = sc.fit_transform(X_train2)
X_test2 = sc.transform(X_test2)

In [70]:
from xgboost import XGBClassifier
classifier = XGBClassifier()
classifier.fit(X_train2, y_train2)

XGBClassifier(base_score=0.5, booster='gbtree', callbacks=None,
              colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric=None, gamma=0, gpu_id=-1, grow_policy='depthwise',
              importance_type=None, interaction_constraints='',
              learning_rate=0.300000012, max_bin=256, max_cat_to_onehot=4,
              max_delta_step=0, max_depth=6, max_leaves=0, min_child_weight=1,
              missing=nan, monotone_constraints='()', n_estimators=100,
              n_jobs=0, num_parallel_tree=1, objective='multi:softprob',
              predictor='auto', random_state=0, reg_alpha=0, ...)

In [74]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test2)
cm = confusion_matrix(y_test2, y_pred)
print(cm)
accuracy_score(y_test2, y_pred)

[[32  2]
 [ 5  1]]


0.825